using server.Models;

namespace server.DAL
{
	public class DbInit
	{

        public static void Seed(IApplicationBuilder app)
        {
            using var serviceScope = app.ApplicationServices.CreateAsyncScope();
            DB context = serviceScope.ServiceProvider.GetRequiredService<DB>();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var uuidUser1 = "1c5ebc08-4f18-11ee-be56-0242ac120002";
            var uuidUser2 = "333dfd94-4f18-11ee-be56-0242ac120002";

            Guid uuidDiscussion1 = Guid.NewGuid();
            Guid uuidDiscussion2 = Guid.NewGuid();
            Guid uuidDiscussion3 = Guid.NewGuid();
            Guid uuidDiscussion4 = Guid.NewGuid();
            Guid uuidDiscussion5 = Guid.NewGuid();
            Guid uuidDiscussion6 = Guid.NewGuid();

            Guid uuidComment1 = Guid.NewGuid();
            Guid uuidComment2 = Guid.NewGuid();
            Guid uuidComment3 = Guid.NewGuid();
            Guid uuidComment4 = Guid.NewGuid();
            Guid uuidComment5 = Guid.NewGuid();
            Guid uuidComment6 = Guid.NewGuid();
            Guid uuidComment7 = Guid.NewGuid();
            Guid uuidComment8 = Guid.NewGuid();
            Guid uuidComment9 = Guid.NewGuid();
            Guid uuidComment10 = Guid.NewGuid();
            Guid uuidComment11 = Guid.NewGuid();
            Guid uuidComment12 = Guid.NewGuid();

            User user1 = new User
            {
                Id = uuidUser1,
                Email = "mck@mail.no"
            };

            User user2 = new User
            {
                Id = uuidUser2,
                Email = "john@doe.com"
            };

            // Disclaimer: All text generated by chatgpt

            Comment comment_1_1 = new Comment(uuidComment1.ToString(), uuidDiscussion1.ToString(), "I'm fascinated by the potential of AI in healthcare. It's incredible how machine learning can help diagnose diseases early and improve patient care.", user2, DateTime.Now.AddYears(-1));
            Comment comment_1_2 = new Comment(uuidComment2.ToString(), uuidDiscussion1.ToString(), "Has anyone tried out a self-driving car yet? I recently did, and the experience was both thrilling and a bit nerve-wracking!", user1, DateTime.Now.AddYears(-1));

            Comment comment_2_1 = new Comment(uuidComment3.ToString(), uuidDiscussion2.ToString(), "Last summer, I hiked to Machu Picchu in Peru. The breathtaking scenery and rich history made it a once-in-a-lifetime experience.\"", user1, DateTime.Now.AddMonths(-1));
            Comment comment_2_2 = new Comment(uuidComment4.ToString(), uuidDiscussion2.ToString(), "I'm planning a road trip across the U.S. Any recommendations for must-visit places along the way?", user2, DateTime.Now.AddMonths(-1));

            Comment comment_3_1 = new Comment(uuidComment5.ToString(), uuidDiscussion3.ToString(), "Yoga has been a game-changer for my mental and physical well-being. It's a fantastic way to de-stress and stay flexible.", user2, DateTime.Now.AddDays(-1));
            Comment comment_3_2 = new Comment(uuidComment6.ToString(), uuidDiscussion3.ToString(), "I've been experimenting with intermittent fasting, and I've seen significant improvements in my energy levels and focus.", user1, DateTime.Now.AddDays(-1));

            Comment comment_4_1 = new Comment(uuidComment7.ToString(), uuidDiscussion4.ToString(), "I just finished reading 'The Great Gatsby.' The symbolism in the book is mind-blowing. What are your thoughts on Jay Gatsby's character?", user1, DateTime.Now.AddDays(-2));
            Comment comment_4_2 = new Comment(uuidComment8.ToString(), uuidDiscussion4.ToString(), "If you're into fantasy, 'The Name of the Wind' by Patrick Rothfuss is a must-read. The storytelling is incredible!", user2, DateTime.Now.AddDays(-2));

            Comment comment_5_1 = new Comment(uuidComment9.ToString(), uuidDiscussion5.ToString(), "Reducing plastic waste is a small step we can all take. I've switched to reusable containers, and it's made a big difference.", user2, DateTime.Now.AddDays(-10));
            Comment comment_5_2 = new Comment(uuidComment10.ToString(), uuidDiscussion5.ToString(), "Have you heard about the recent reforestation efforts in Brazil? It's inspiring to see people coming together to protect the Amazon.", user1, DateTime.Now.AddDays(-10));

            Comment comment_6_1 = new Comment(uuidComment11.ToString(), uuidDiscussion6.ToString(), "I'm working on a new acrylic painting inspired by nature. There's something therapeutic about expressing myself through art.", user1, DateTime.Now.AddMonths(-2));
            Comment comment_6_2 = new Comment(uuidComment12.ToString(), uuidDiscussion6.ToString(), "Writing poetry is my passion. It allows me to convey emotions and thoughts in a way that words alone can't capture.\"", user2, DateTime.Now.AddMonths(-2));

            Discussion discussion1 = new Discussion(uuidDiscussion1.ToString(), "Technology Trends", "Discuss the latest advancements in technology, such as AI, blockchain, and IoT, and their impact on various industries.\n\nExplore the cutting-edge developments and their potential to shape our future.", user1, DateTime.Now.AddMonths(-3), DateTime.Now.AddMonths(-3));
            Discussion discussion2 = new Discussion(uuidDiscussion2.ToString(), "Travel Adventures", "Share your travel experiences, from hidden gems to popular destinations, and exchange tips and stories with fellow adventurers.\n\nEmbark on a virtual journey to discover new places and cultures.", user2, DateTime.Now.AddHours(-10), DateTime.Now.AddHours(-10));
            Discussion discussion3 = new Discussion(uuidDiscussion3.ToString(), "Health and Wellness", "Join discussions on fitness, nutrition, mental health, and holistic well-being to improve your overall health.\n\nDiscover strategies to lead a healthier and more balanced lifestyle.", user1, DateTime.Now.AddDays(-5), DateTime.Now.AddDays(-5));
            Discussion discussion4 = new Discussion(uuidDiscussion4.ToString(), "Book Club", "Dive into the world of literature, from classic novels to contemporary bestsellers, and engage in lively book discussions.\n\nGet lost in the pages of captivating stories and thought-provoking literature.", user2, DateTime.Now.AddDays(-17), DateTime.Now.AddDays(-17));
            Discussion discussion5 = new Discussion(uuidDiscussion5.ToString(), "Environmental Sustainability", "Explore topics related to eco-friendly practices, climate change, and conservation efforts to protect our planet.\n\nJoin the conversation about creating a sustainable future for generations to come.", user1, DateTime.Now, DateTime.Now);
            Discussion discussion6 = new Discussion(uuidDiscussion6.ToString(), "Art and Creativity", "Connect with fellow artists, photographers, writers, and creatives to share your work, ideas, and inspiration.\n\nUnleash your creativity and inspire others through artistic expression.", user2, DateTime.Now.AddDays(-7), DateTime.Now.AddDays(-7));

            if (!context.Users.Any())
            {
                var users = new List<User>
                {
                    user1,
                    user2,
                };
                context.AddRange(users);
                context.SaveChanges();
            }

            if (!context.Discussions.Any())
            {
                var discussions = new List<Discussion>
                {
                    discussion1,
                    discussion2,
                    discussion3,
                    discussion4,
                    discussion5,
                    discussion6,
                };
                context.AddRange(discussions);
                context.SaveChanges();
            }

            if (!context.Comments.Any()) {
                var comments = new List<Comment>
                {
                    comment_1_1,
                    comment_1_2,
                    comment_2_1,
                    comment_2_2,
                    comment_3_1,
                    comment_3_2,
                    comment_4_1,
                    comment_4_2,
                    comment_5_1,
                    comment_5_2,
                    comment_6_1,
                    comment_6_2,
                };
                context.AddRange(comments);
                context.SaveChanges();
            }

            context.SaveChanges();
        }

	}
}

