export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Discussions } from "./Discussions";
export { default as Detail } from "./Detail";
export { default as CreateDiscussion } from "./CreateDiscussion";
export { default as UpdateDiscussion } from "./UpdateDiscussion";
export { default as DeleteDiscussion } from "./DeleteDiscussion";
export { default as Logout } from "./Logout";
export { default as CreateComment } from "./CreateComment";
